apiVersion: v1
kind: Service
metadata:
  name: poc-streamlit
  labels:
    app: poc-streamlit
spec:
  selector:
    app: poc-streamlit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: ClusterIP
