name: CI — Build and push Docker image to JFrog

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: poc-streamlit

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Login to JFrog Docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.JFROG_REGISTRY }}
          username: ${{ secrets.JFROG_USERNAME }}
          password: ${{ secrets.JFROG_PASSWORD }}

      - name: Build and push image to JFrog
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            ${{ secrets.JFROG_REGISTRY }}/${{ secrets.JFROG_REPO }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.JFROG_REGISTRY }}/${{ secrets.JFROG_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image info
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "Pushed images:"
          echo "${{ secrets.JFROG_REGISTRY }}/${{ secrets.JFROG_REPO }}/${{ env.IMAGE_NAME }}:latest"
          echo "${{ secrets.JFROG_REGISTRY }}/${{ secrets.JFROG_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
